In [3]:
import numpy as np

In [4]:
def qr_decompose(A):
    # A is n x n matrix
    # ------------ TODO -----------------------------
    # you may not use numpy.linalg.qr function

    # return Q, R
    return np.eye(A.shape[0]), np.eye(A.shape[0])

In [5]:
def get_elliptic_mat(n):
    # get a matrix
    A = 2 * np.identity(n)
    neg_ones = -np.identity(n - 1)
    A[1: n, 0: n - 1] += neg_ones
    A[0: n - 1, 1: n] += neg_ones
    A = A / ((n + 1) ** 2)
    return A

def check_qr(Q, R, A):
    # check if QR decomposition is done properly
    if not np.allclose(Q @ R, A):
        print('Q * R is \n{}\n, not A'.format(Q @ R))
    elif not np.allclose(Q.T @ Q, np.eye(Q.shape[0])):
        print('Q is not orthogonal')
    elif not np.allclose(R, np.triu(R)):
        print('R is not a upper triangular matrix')
    else:
        print('Correct!!!')
        print('Q: {}'.format(Q))
        print('R: {}'.format(R))

In [6]:
n = 5
A = get_elliptic_mat(n)
Q, R = qr_decompose(A)
check_qr(Q, R, A)

Q * R is 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
, not A
